In [8]:
with open('untitled.txt') as practicefile:
    contents=practicefile.read()
    print(contents.rstrip())

Name: Haris Amin
F/Name: Muhammad Amin
University: QUEST
Phone no: +92 3321127718
Expert in Artificial Intelligence
Experience: 1 Year


In [9]:
with open('untitled.txt') as practicefile:
    contents=practicefile.read()
    print(contents.rstrip())

Name: Haris Amin
F/Name: Muhammad Amin
University: QUEST
Phone no: +92 3321127718
Expert in Artificial Intelligence
Experience: 1 Year


In [10]:
import math as mymath
print(mymath.pi)

3.141592653589793


In [5]:
from math import *
print(pi)

3.141592653589793


In [16]:
from math import *
print(pi)
print(floor(5.7))
print(ceil(5.7))

3.141592653589793
5
6


In [1]:
import import_ipynb
import untitled2
untitled.add(5,3)

ModuleNotFoundError: No module named 'import_ipynb'

In [5]:
import numpy as np

data = np.random.randn(3,5)
print(data,"\n")
print(data+data , '\n')
print(data * 10 , '\n')
print(data.shape, '\n')
print(data.dtype , '\n')
print(data.ndim , '\n')

[[-0.36222728  0.37676009 -0.32646008  1.07795406 -0.1437121 ]
 [-1.67097606 -0.21752607 -0.62318193 -1.3860198  -1.47585859]
 [-0.49994113 -0.20248664  0.03416671 -1.62399579  1.27692791]] 

[[-0.72445456  0.75352019 -0.65292015  2.15590812 -0.2874242 ]
 [-3.34195213 -0.43505215 -1.24636387 -2.77203959 -2.95171717]
 [-0.99988227 -0.40497328  0.06833342 -3.24799158  2.55385583]] 

[[ -3.62227278   3.76760094  -3.26460076  10.77954059  -1.43712099]
 [-16.70976064  -2.17526073  -6.23181934 -13.86019796 -14.75858587]
 [ -4.99941133  -2.02486639   0.34166708 -16.23995788  12.76927913]] 

(3, 5) 

float64 

2 



In [2]:
import numpy as np
print(np.random.randn(2,4))

print(np.random.randn(3,2,3))
print(np.maximum(2,2))

print(np.zeros(10))
print(np.pi)
print(np.pi*3)
#print(np.)

[[-0.6671011  -0.13916421  1.01906016 -1.66770964]
 [-0.01606859 -1.35541875  0.08935923 -1.28200242]]
[[[ 0.54961973 -0.32492421 -0.51355707]
  [-1.62085412  1.61756341 -1.23789092]]

 [[ 0.63409298 -0.42774948 -0.26270636]
  [-1.60315594 -0.94505004  0.43395117]]

 [[-0.97818415  1.45924958  1.05861718]
  [-2.85764248 -1.13526745 -1.80596583]]]
2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3.141592653589793
9.42477796076938
